name: eproject
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_spinkit: ^5.1.0
  device_info_plus: ^8.1.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  shimmer: ^2.0.0
  intl: ^0.17.0
  syncfusion_flutter_charts: ^20.4.53
  curved_navigation_bar: ^1.0.3
  location: ^4.4.0
  permission_handler: ^10.2.0
  quickalert: ^1.0.1
  iconly: ^1.0.1
  zoom_tap_animation: ^1.1.0

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/